version: '3.3'
services:
  sampleapp:
    build:
      context: .
      dockerfile: SampleDockerFile
    image: sampleapp:assembledebug
    volumes:
      - type: bind
        source: .
        target: /sampleapp
    command: /sampleapp/start.sh
