version: '3.3'
services:
  sampleapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /sampleapp/app/build/outputs/apk/debug
    command: /sampleapp/start.sh
