version: '3.3'
services:
  sampleapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sampleapp:assembledebug
    volumes:
      - type: bind
        source: .
        target: /sampleapp
    command: /bin/bash -c "chmod a+x /sampleapp/start.sh && /sampleapp/start.sh"
